import "../globals.css"

import Link from "next/link"
import { Inter } from "next/font/google"
import { redirect } from "next/navigation"
import { getServerSession } from "next-auth"

import { authOptions } from "@/lib/auth"
import { PATHS, SITE_NAME } from "@/configs"

import Logo from "@/components/Logo"
import { ThemeProvider } from "@/components/ThemeProvider"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: `Đăng nhập vào ${SITE_NAME}`,
  description: "Generated by Next.js",
}

export default async function AuthLayout({ children }) {
  const session = await getServerSession(authOptions)
  if (session) return redirect(PATHS.home)

  return (
    <html lang="vi" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider attribute="class" enableSystem>
          <div className="h-screen flex flex-col">
            <div className="border-b bg-background/80 backdrop-blur-xl z-50 h-16">
              <header className="sticky top-0 flex container h-full items-center justify-between">
                <Logo />
                <Link className="text-foreground/60 hover:text-foreground transition-colors" href="/">
                  Liên hệ
                </Link>
              </header>
            </div>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
